const {createClient}=require('@supabase/supabase-js');const Stripe=require('stripe');
const U=process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL,K=process.env.SUPABASE_SECRET_KEY,P=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_PUBLISHABLE_KEY,E=String(process.env.OWNER_ADMIN_EMAIL||'').toLowerCase().trim(),SK=process.env.STRIPE_TEST_SECRET_KEY||process.env.STRIPE_SECRET_KEY;
function j(r,s,b){r.statusCode=s;r.setHeader('content-type','application/json');r.end(JSON.stringify(b))}function path(req){try{return new URL(req.url,'http://x').pathname}catch{return req.url}}async function body(req){if(req.body&&typeof req.body==='object')return req.body;if(typeof req.body==='string')return JSON.parse(req.body||'{}');let s='';for await(const c of req)s+=c;return JSON.parse(s||'{}')}function sb(){return createClient(U,K,{auth:{persistSession:false}})}function nights(a,b){return Math.round((new Date(b+'T00:00:00Z')-new Date(a+'T00:00:00Z'))/86400000)}function code(){return'AIP-'+Math.random().toString(36).slice(2,8).toUpperCase()+'-'+Date.now().toString().slice(-6)}function base(req){return`${req.headers['x-forwarded-proto']||'https'}://${req.headers['x-forwarded-host']||req.headers.host}`}
async function admin(req,c){if(!E){let e=Error('OWNER_ADMIN_EMAIL is not configured yet.');e.status=503;throw e}let h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):'',{data,error}=await c.auth.getUser(t),email=String(data?.user?.email||'').toLowerCase();if(error||!data?.user){let e=Error('Please sign in.');e.status=401;throw e}if(email!==E){let e=Error('This account is not authorized.');e.status=403;throw e}return data.user}
function clean(b){let x={};for(let k of['name','location','description'])if(k in b)x[k]=b[k]?String(b[k]).trim():null;for(let k of['nightly_rate','cleaning_fee','tax_rate','max_guests','bedrooms','bathrooms'])if(k in b)x[k]=b[k]===null?null:Number(b[k]);if('active'in b)x.active=!!b.active;return x}
async function av(c,id,ci,co,g){let n=nights(ci,co);if(!id||!ci||!co||n<1||n>60)return{available:false,error:'Invalid dates.'};let{data:p,error:pe}=await c.from('properties').select('*').eq('id',id).eq('active',true).single();if(pe||!p)return{available:false,error:'Property not found.'};if(Number(g||1)>Number(p.max_guests||1))return{available:false,error:`This property allows up to ${p.max_guests} guests.`};let{data:bl,error:be}=await c.from('blocked_dates').select('id').eq('property_id',id).lt('start_date',co).gt('end_date',ci).limit(1);if(be)throw be;if(bl?.length)return{available:false,error:'Those dates are blocked.'};let cutoff=new Date(Date.now()-1800000).toISOString(),{data:rs,error:re}=await c.from('reservations').select('id,status,created_at').eq('property_id',id).lt('check_in',co).gt('check_out',ci).in('status',['confirmed','paid','pending']);if(re)throw re;if((rs||[]).some(r=>r.status!=='pending'||String(r.created_at)>=cutoff))return{available:false,error:'Those dates are already reserved.'};return{available:true,property:p,nights:n}}
module.exports=async(req,res)=>{let p=path(req),c=sb();try{
if(p==='/api/config'&&req.method==='GET')return j(res,200,{supabaseUrl:U,supabasePublishableKey:P});
if(p==='/api/properties'&&req.method==='GET'){let{data,error}=await c.from('properties').select('*').eq('active',true).order('created_at');if(error)throw error;return j(res,200,{properties:data||[]})}
if(p==='/api/availability'&&req.method==='GET'){let u=new URL(req.url,'http://x'),r=await av(c,u.searchParams.get('propertyId'),u.searchParams.get('checkIn'),u.searchParams.get('checkOut'),Number(u.searchParams.get('guests')||1));return j(res,200,r)}
if(p==='/api/create-checkout'&&req.method==='POST'){if(!SK)return j(res,503,{error:'Stripe checkout is not configured yet.'});if(String(SK).startsWith('sk_live_')&&process.env.ENABLE_LIVE_CHECKOUT!=='true')return j(res,503,{error:'Checkout is ready, but live charging is locked until final payment testing is completed.'});let b=await body(req);if(!b.guestName||!b.guestEmail)return j(res,400,{error:'Name and email are required.'});let r=await av(c,b.propertyId,b.checkIn,b.checkOut,Number(b.guests||1));if(!r.available)return j(res,409,{error:r.error});let pr=r.property,n=r.nights,sub=Number(pr.nightly_rate||0)*n,cl=Number(pr.cleaning_fee||0),tx=(sub+cl)*Number(pr.tax_rate||0),total=sub+cl+tx,conf=code();let{data:h,error:he}=await c.rpc('create_reservation_hold',{p_confirmation_code:conf,p_property_id:pr.id,p_guest_name:String(b.guestName).trim(),p_guest_email:String(b.guestEmail).trim().toLowerCase(),p_guest_phone:b.guestPhone||null,p_check_in:b.checkIn,p_check_out:b.checkOut,p_guests:Number(b.guests||1),p_nightly_subtotal:sub,p_cleaning_fee:cl,p_taxes:tx,p_total_amount:total});if(he){let m=String(he.message||'');if(m.includes('DATES_UNAVAILABLE')||m.includes('BLOCKED_DATES'))return j(res,409,{error:'Those dates are no longer available.'});throw he}let rid=Array.isArray(h)?h[0]?.reservation_id:(h?.reservation_id||h),st=new Stripe(SK),session=await st.checkout.sessions.create({mode:'payment',customer_email:String(b.guestEmail).trim().toLowerCase(),expires_at:Math.floor(Date.now()/1000)+1800,line_items:[{quantity:1,price_data:{currency:'usd',unit_amount:Math.round(total*100),product_data:{name:`${pr.name} — ${n} night${n===1?'':'s'}`,description:`${b.checkIn} to ${b.checkOut}`}}}],metadata:{reservation_id:String(rid),confirmation_code:conf,property_id:pr.id},success_url:`${base(req)}/?checkout=success&session_id={CHECKOUT_SESSION_ID}`,cancel_url:`${base(req)}/?checkout=cancelled`});await c.from('reservations').update({stripe_checkout_session_id:session.id}).eq('id',rid);return j(res,200,{url:session.url})}
if(p==='/api/finalize'&&req.method==='GET'){if(!SK)return j(res,503,{error:'Stripe is not configured.'});let u=new URL(req.url,'http://x'),sid=u.searchParams.get('session_id');if(!sid)return j(res,400,{error:'Missing session.'});let st=new Stripe(SK),session=await st.checkout.sessions.retrieve(sid);if(session.payment_status!=='paid')return j(res,200,{confirmed:false});let rid=session.metadata?.reservation_id,pi=typeof session.payment_intent==='string'?session.payment_intent:session.payment_intent?.id;if(!rid)return j(res,400,{error:'Reservation metadata missing.'});await c.from('reservations').update({status:'confirmed',stripe_payment_intent_id:pi||null}).eq('id',rid);if(pi)await c.from('payments').upsert({reservation_id:rid,stripe_payment_intent_id:pi,amount:Number(session.amount_total||0)/100,currency:session.currency||'usd',status:'paid'},{onConflict:'stripe_payment_intent_id'});return j(res,200,{confirmed:true,confirmationCode:session.metadata?.confirmation_code||null})}
if(p==='/api/admin/me'&&req.method==='GET'){let u=await admin(req,c);return j(res,200,{email:u.email})}
if(p==='/api/admin/properties'&&req.method==='GET'){await admin(req,c);let{data,error}=await c.from('properties').select('*').order('created_at',{ascending:false});if(error)throw error;return j(res,200,{properties:data||[]})}
if(p==='/api/admin/properties'&&req.method==='POST'){await admin(req,c);let x=clean(await body(req));if(!x.name)return j(res,400,{error:'Property name is required.'});let{data,error}=await c.from('properties').insert(x).select('*').single();if(error)throw error;return j(res,201,{property:data})}
let pm=p.match(/^\/api\/admin\/properties\/([0-9a-f-]+)$/i);if(pm&&req.method==='PATCH'){await admin(req,c);let{data,error}=await c.from('properties').update(clean(await body(req))).eq('id',pm[1]).select('*').single();if(error)throw error;return j(res,200,{property:data})}
if(p==='/api/admin/blocked-dates'&&req.method==='GET'){await admin(req,c);let{data,error}=await c.from('blocked_dates').select('id,property_id,start_date,end_date,reason,properties(name)').order('start_date');if(error)throw error;return j(res,200,{blockedDates:data||[]})}
if(p==='/api/admin/blocked-dates'&&req.method==='POST'){await admin(req,c);let b=await body(req),{data,error}=await c.from('blocked_dates').insert({property_id:b.property_id,start_date:b.start_date,end_date:b.end_date,reason:b.reason||null}).select('*').single();if(error)throw error;return j(res,201,{blockedDate:data})}
let bm=p.match(/^\/api\/admin\/blocked-dates\/([0-9a-f-]+)$/i);if(bm&&req.method==='DELETE'){await admin(req,c);let{error}=await c.from('blocked_dates').delete().eq('id',bm[1]);if(error)throw error;return j(res,200,{ok:true})}
if(p==='/api/admin/reservations'&&req.method==='GET'){await admin(req,c);let{data,error}=await c.from('reservations').select('id,confirmation_code,guest_name,guest_email,guest_phone,check_in,check_out,guests,total_amount,status,created_at,properties(name)').order('created_at',{ascending:false});if(error)throw error;return j(res,200,{reservations:data||[]})}
return j(res,404,{error:'Not found'})}catch(e){console.error(e);return j(res,e.status||500,{error:e.status?e.message:'Server error. Please try again.'})}};